// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgglaxqxspyqiaoplfsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnZ2xheHF4c3B5cWlhb3BsZnN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTg4OTEsImV4cCI6MjA3MjI5NDg5MX0.BsaBgdzR4UGeRgs3HhWGXctx3j2SF-wJlLdHkMSkKM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});